name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag redis:6.2.7-alpine && docker push docker.io/jiamiao442/redis:6.2.7-alpine

   # - name: Push the Docker image
   #   run: docker push docker.io/jiamiao442/redis:6.2.7-alpine
